/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	v1 "k8s.io/api/core/v1"
)

// PodQOSResourceRequestApplyConfiguration represents an declarative configuration of the PodQOSResourceRequest type for use
// with apply.
type PodQOSResourceRequestApplyConfiguration struct {
	Name  *v1.QOSResourceName `json:"name,omitempty"`
	Class *string             `json:"class,omitempty"`
}

// PodQOSResourceRequestApplyConfiguration constructs an declarative configuration of the PodQOSResourceRequest type for use with
// apply.
func PodQOSResourceRequest() *PodQOSResourceRequestApplyConfiguration {
	return &PodQOSResourceRequestApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *PodQOSResourceRequestApplyConfiguration) WithName(value v1.QOSResourceName) *PodQOSResourceRequestApplyConfiguration {
	b.Name = &value
	return b
}

// WithClass sets the Class field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Class field is set to the value of the last call.
func (b *PodQOSResourceRequestApplyConfiguration) WithClass(value string) *PodQOSResourceRequestApplyConfiguration {
	b.Class = &value
	return b
}
