/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	v1 "k8s.io/api/core/v1"
)

// QOSResourceInfoApplyConfiguration represents an declarative configuration of the QOSResourceInfo type for use
// with apply.
type QOSResourceInfoApplyConfiguration struct {
	Name    *v1.QOSResourceName                      `json:"name,omitempty"`
	Mutable *bool                                    `json:"mutable,omitempty"`
	Classes []QOSResourceClassInfoApplyConfiguration `json:"classes,omitempty"`
}

// QOSResourceInfoApplyConfiguration constructs an declarative configuration of the QOSResourceInfo type for use with
// apply.
func QOSResourceInfo() *QOSResourceInfoApplyConfiguration {
	return &QOSResourceInfoApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *QOSResourceInfoApplyConfiguration) WithName(value v1.QOSResourceName) *QOSResourceInfoApplyConfiguration {
	b.Name = &value
	return b
}

// WithMutable sets the Mutable field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Mutable field is set to the value of the last call.
func (b *QOSResourceInfoApplyConfiguration) WithMutable(value bool) *QOSResourceInfoApplyConfiguration {
	b.Mutable = &value
	return b
}

// WithClasses adds the given value to the Classes field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Classes field.
func (b *QOSResourceInfoApplyConfiguration) WithClasses(values ...*QOSResourceClassInfoApplyConfiguration) *QOSResourceInfoApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithClasses")
		}
		b.Classes = append(b.Classes, *values[i])
	}
	return b
}
