/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// QoSResourceStatusApplyConfiguration represents an declarative configuration of the QoSResourceStatus type for use
// with apply.
type QoSResourceStatusApplyConfiguration struct {
	PodQoSResources       []QoSResourceInfoApplyConfiguration `json:"podQoSResources,omitempty"`
	ContainerQoSResources []QoSResourceInfoApplyConfiguration `json:"containerQoSResources,omitempty"`
}

// QoSResourceStatusApplyConfiguration constructs an declarative configuration of the QoSResourceStatus type for use with
// apply.
func QoSResourceStatus() *QoSResourceStatusApplyConfiguration {
	return &QoSResourceStatusApplyConfiguration{}
}

// WithPodQoSResources adds the given value to the PodQoSResources field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the PodQoSResources field.
func (b *QoSResourceStatusApplyConfiguration) WithPodQoSResources(values ...*QoSResourceInfoApplyConfiguration) *QoSResourceStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithPodQoSResources")
		}
		b.PodQoSResources = append(b.PodQoSResources, *values[i])
	}
	return b
}

// WithContainerQoSResources adds the given value to the ContainerQoSResources field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ContainerQoSResources field.
func (b *QoSResourceStatusApplyConfiguration) WithContainerQoSResources(values ...*QoSResourceInfoApplyConfiguration) *QoSResourceStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithContainerQoSResources")
		}
		b.ContainerQoSResources = append(b.ContainerQoSResources, *values[i])
	}
	return b
}
