/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// QOSResourceQuotaApplyConfiguration represents an declarative configuration of the QOSResourceQuota type for use
// with apply.
type QOSResourceQuotaApplyConfiguration struct {
	Pod       []AllowedQOSResourceApplyConfiguration `json:"pod,omitempty"`
	Container []AllowedQOSResourceApplyConfiguration `json:"container,omitempty"`
}

// QOSResourceQuotaApplyConfiguration constructs an declarative configuration of the QOSResourceQuota type for use with
// apply.
func QOSResourceQuota() *QOSResourceQuotaApplyConfiguration {
	return &QOSResourceQuotaApplyConfiguration{}
}

// WithPod adds the given value to the Pod field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Pod field.
func (b *QOSResourceQuotaApplyConfiguration) WithPod(values ...*AllowedQOSResourceApplyConfiguration) *QOSResourceQuotaApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithPod")
		}
		b.Pod = append(b.Pod, *values[i])
	}
	return b
}

// WithContainer adds the given value to the Container field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Container field.
func (b *QOSResourceQuotaApplyConfiguration) WithContainer(values ...*AllowedQOSResourceApplyConfiguration) *QOSResourceQuotaApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithContainer")
		}
		b.Container = append(b.Container, *values[i])
	}
	return b
}
