apiVersion: v1
kind: Pod
metadata:
  name: demo
spec:
  containers:
  - name: cnt-1
    image: k8s.gcr.io/busybox
    command:
      - "/bin/sh"
      - "-c"
    args:
      - |
        cat /etc/hosts;
        while :; do date; sleep 10; done
    resources:
      requests:
        cpu: 100m
      limits:
        cpu: 200m

  - name: cnt-2
    image: k8s.gcr.io/busybox
    command:
      - "/bin/sh"
      - "-c"
    args:
      - |
        cat /etc/hosts;
        while :; do date; sleep 10; done
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
