apiVersion: v1
kind: Pod
metadata:
  name: pod-level-res
spec:
  resources:
    classes:
      dummy-2: silver
  containers:
  - name: pod-level-res
    image: k8s.gcr.io/pause
    resources:
      classes:
        rdt: besteffort
        blockio: low-prio

