apiVersion: v1
kind: Pod
metadata:
  name: demo
spec:
  containers:
  - name: cnt-1
    image: k8s.gcr.io/pause
    resources:
      qosResources:
      - name: rdt
        class: gold
      - name: blockio
        class: low-prio
