apiVersion: v1
kind: Pod
metadata:
  name: demo
spec:
  qosResources:
  - name: podres-notexists
    class: cls-1
  - name: net
    class: foo
  containers:
  - name: foo
    image: k8s.gcr.io/pause
    resources:
      qosResources:
      - name: rdt
        class: foo
      - name: blockio
        class: bar
      - name: dummy-qos
        class: baz
