apiVersion: v1
kind: Pod
metadata:
  name: pod-level-res
spec:
  resources:
    qosResources:
      podres-1: qos-a
  containers:
  - name: pod-level-res
    image: k8s.gcr.io/pause
    resources:
      qosResources:
        rdt: besteffort
        blockio: low-prio

