apiVersion: v1
kind: ResourceQuota
metadata:
  name: demo
spec:
  qosResources:
    pod:
      - name: podres-1
        classes:
          - qos-a
          - qos-b
    container:
      - name: rdt
        classes:
          - bronze
      - name: blockio
        classes:
          - normal
          - low-prio
      - name: dummy-1
        classes:
          - class-b
          - class-c
          - class-d
