apiVersion: v1
kind: Pod
metadata:
  name: denied
spec:
  resources:
    qosResources:
      podres-1: qos-a
      podres-2: cls-1
  containers:
  - name: container-1
    image: k8s.gcr.io/pause
    resources:
      qosResources:
        rdt: besteffort
        dummy-1: class-b
        dummy-2: platinum

